### ISSUE TITLE
[PE-D][Tester A] Duplicate prefix for different meanings

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#175] opened 2024-04-05 22:26 UTC
The prefix for tag attached to patient and appointment type are both the same(both are t/), would it be better to distinguish the prefixes of these two parameters in order to avoid user comprehension issues? For example change the prefix of appointment type to type/ instead of t/
![image.png](https://raw.githubusercontent.com/FangRuoqing/ped/main/files/8fcc38ff-3e5f-456e-8bce-6ac9f5f79452.png)

![image.png](https://raw.githubusercontent.com/FangRuoqing/ped/main/files/919f99d6-dd94-4915-86ad-4c07ece419f5.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: FangRuoqing/ped#7

**Comment by dayn-1** [comment] 2024-04-09 16:33
Won't Fix as intended behaviour. Both parameters have similar function of categorising a patient or appointment.

Updated FAQ in UG.

**Closed as completed by dayn-1** 2024-04-09 16:33 UTC
Labels: PED.Invalid
