### ISSUE TITLE
[PE-D][Tester D] Limited character count for names

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#136] opened 2024-04-05 19:20 UTC
Character count for name is too low. CLInic only accepts up to 55 characters and is unable to account for very long names that are quite common in SG 

e.g. Indian names that contain family name and parent's name together with their own names (Chandrasekaran Muthusamy Balakrishnan SO Chandrasekaran Sanjay)

e.g. Picasso's full name (Pablo Diego Jose Francisco de Paula Juan Nepomuceno Maria de los Remedios Cipriano de la Santisima Trinidad Ruiz y Picasso)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: delishad21/ped#7

**Comment by dayn-1** [comment] 2024-04-09 15:17
Won't Fix as intended behaviour.

Singaporean names have a limit of 54 characters due to limited space on the physical IC. Clinic assistants use ICs to register patients.
Addressed in plans for future enhancements by @ThatGirlJam to accommodate foreign patients.

**Closed as completed by dayn-1** 2024-04-09 15:17 UTC
Labels: PED.Invalid
