### ISSUE TITLE
[PE-D][Tester D] Foreign phone numbers are not accepted.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#165] opened 2024-04-05 21:57 UTC
Possibility for Foreigners with no local phone number to also visit clinics. Without the ability to key in foreign numbers, the clinic loses a crucial avenue through which they can contact the patient. Furthermore, as phone numbers are a compulsory data field when adding patients, it is not even possible to exclude the phone number from the foreign patient's record, leading to the user needing to save a dummy number just to keep a record of the foreign patient.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: delishad21/ped#11

**Comment by dayn-1** [comment] 2024-04-09 15:02
Won't Fix as it is intended behaviour based on current design, clinic may have other limitations requiring phone numbers to be local ones.

@ThatGirlJam added compatibility with foreign patients into the plans for future enhancements.

**Closed as completed by dayn-1** 2024-04-09 15:02 UTC
Labels: PED.Invalid
