### ISSUE TITLE
[PE-D][Tester D] App makes the email and phone fields compulsory.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-3/tp#174] opened 2024-04-05 22:12 UTC
Under a situation where a patient might not have an email or a phone number, the user would have to key in dummy emails or dummy phone numbers just to keep a patient's record in the application. This may happen in situations where a patient might be a kid and has no phone number, or for pioneer generations that are not internet savvy enough to set up an email account.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: delishad21/ped#20

**Comment by dayn-1** [comment] 2024-04-09 14:34
Won't fix as it is intended behaviour. Emergency contact details are necessary to contact patients. For elderly and children, phone numbers can be filed by their family members. 

@ThatGirlJam has updated FAQ to make this clear.

**Closed as completed by dayn-1** 2024-04-09 14:34 UTC
Labels: severity.Low, PED.Invalid
